services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_DATABASE: development
      MONGODB_INITDB_ROOT_PASSWORD: pass
    networks: 
      - mongodb-network
    ports:
      - '27017:27017'
    volumes:
      - '/home/olivbull/code/go/stock-agent/mongodb/data:/data/db:rw'
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - mongodb
    networks: 
      - mongodb-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    ports:
      - '8081:8081'

networks:
  mongodb-network:
    driver: bridge